version: '3.8'
services:
  postgis:
    image: postgis/postgis:15-3.4-alpine
    container_name: postgis
    ports:
      - '5432:5432'
    env_file:
      - ./postgis.env 
    volumes:
      - pg_data:/var/lib/postgresql/data
  neo4j:
    image: neo4j:5.10.0-community-bullseye
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    env_file:
      - ./neo4j.env 
    volumes:
      - neo4j_data:/var/lib/neo4j/data
      - ./obu-data:/var/lib/neo4j/import

  nginx_react:
    build: 
      context: '../frontend'
      args:
        REACT_APP_EXPRESS_BASE_URL: https://8087-cxnturi0n-trafficanalyz-jh0b99dxmke.ws-eu104.gitpod.io
        REACT_APP_EXPRESS_API_PREFIX: /traffic-analyzer/api
    container_name: nginx_react
    ports:
      - "80:80"

  nodejs_express:
    build: '../backend'
    container_name: nodejs_express
    ports:
      - "8087:8087"
    env_file:
      - ./nodejs_express.env
    depends_on:
      - neo4j
      - postgis
    restart: on-failure
   

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4
  #   ports:
  #     - '5555:80'
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=f.cinicolo@studenti.unina.it
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin/data
  #   depends_on:
  #     - postgis


volumes:
  pg_data: {}
  neo4j_data: {}
  pgadmin_data: {}
